### PR TITLE
Fix broken firefox.json and chrome.json (#2)

### PR DESCRIPTION
**Pull request by blockindouches**
* Update .chromium.json

* Update .firefox.json

### CODE REVIEW

**Comment by MaNaReaver** [comment]
Hello,

Thank you for working on this fork, it's very appreciated since the original extension has had no updates since 2 years. I had been trying to figure out how to make the extension work, but was unable to use it without errors and issues, and possibly due to a lack of understanding on how to build extensions from source code. Would it be possible for you to create a release build for chromium, such that it's easier to work-around and use the extension successfully?

Best regards.

**Comment by blockindouches** [comment]
**EDIT: has been determined that no Chromium version works with the extension now due to changes in Chromium. Firefox Developer, Librewolf, and other Firefox derivatives still work at this time (except for regular Firefox, or Firefox Beta.)**

Hi there,

As partially detailed here:

https://github.com/blockindouches/doucheblockplus#readme

it may be a problem getting it signed for easy installation in any browser due to the shift from Manifest v2 extensions to Manifest v3. I'm simply not familiar enough to make the changes to convert to v3 right now, and so it likely won't get approved for the Chrome store, and can only be installed in developer mode.

**EDIT: LOADS BUT DOES NOT WORK IN ANY CHROMIUM BROWSER NOW, DUE TO CHANGES IN CHROMIUM**
You'd have to use the "Load unpacked" option once developer mode is turned on, then select the extension folder (a manually installed extension cannot be a zipped archive like for Firefox). Even then, no idea how long it would continue to work in Chrome before they straight disable Manifest v2 extensions, previously approved or not. It may have a longer shelf life with other Chromium browsers that don't follow Google's lead, but unsure.

**EDIT: IT DOES STILL WORK IN FIREFOX-BASED BROWSERS, AT THIS TIME**
Using [Firefox Developer](https://www.mozilla.org/en-US/firefox/developer/) for automatic updates, or [Librewolf](https://librewolf.net/), or an [unbranded build of Firefox](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) with no autoupdates, is probably a better option for longevity with the current Manifest v2 format, as they've signaled they intended to continue supporting v2 (who knows how long), but right now it's still not approved in the Firefox plugins store, because there's a certain action the old code does of directly setting content in element HTML fields to label the GUI, which has been deprecated and no longer usually allowed, and I haven't yet figured out how to get around that yet for automatic approval, and keep it looking the same. I possibly could get it approved in review, but the documentation they want is a bit much for the moment.

I personally may be using a unbranded build of Firefox if nothing else, as you can manually override to install the extension, and then disable updates if new versions don't allow Manifest v2 anymore, and just use that old version as a dedicated Twitter browser with DoucheBlock, but that's just me. (**EDIT: probably [Librewolf](https://librewolf.net/) now since it has portable versions and/or you can optionally enable autoupdates for a regular install.**)


**I'll update the readme later, but to build the new v2 from the master yourself on Windows (which doesn't have any experimental code to fix the HTML issue or to convert to Manifest v3):**

- Install the [LTS version of node.js - 18.17.x](https://nodejs.org/en)
    - be sure to select any options to add it to the PATH and/or for "All Users", etc
- Download the [master.zip of the source](https://github.com/blockindouches/doucheblockplus/archive/refs/heads/master.zip)
    - or use the "<> Code" button on the main repo screen and click "Download ZIP"
- Unzip the master.zip into a folder
- Open cmd.exe
- Navigate to the folder containing the source code files
- run "npm install" to download dependencies
- run "npm audit fix" to update required deprecated components
- run "npm run build:ff" to create a Firefox extension as firefox.zip
    - or "npm run start:ff" to temporarily load it in debugging mode
- **EDIT: LOADS BUT DOES NOT WORK IN ANY CHROMIUM BROWSER NOW, DUE TO CHANGES IN CHROMIUM**
    - run "npm run build" to create a Chrome extension as chrome.zip
    - or "npm run start" to temporarily load it in debugging mode



**To load in Firefox Developer, Librewolf, or Firefox unbranded (cannot override in regular Firefox or Beta):**
- you first have to override the requirement for signatures on manually installed extensions (these directions come from the FAQ under the [unbranded builds](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds)):
    - type "about:config" in the address bar and press Enter
    - search "xpinstall.signatures.required"
    - double-click that option to set it to false
    - note that re-enabling this will automatically disable all unsigned extensions
- in extension manager, click the gear icon, then "Install Add-On from File..."
- select the firefox.zip extension you've generated
- it will probably warn you about it being unsigned, etc



**To load in Chrome or Chromium browsers:**
- **EDIT: LOADS BUT DOES NOT WORK IN ANY CHROMIUM BROWSER NOW, DUE TO CHANGES IN CHROMIUM**
    - unzip the chrome.zip to a folder
    - in the browser extension manager, turn on developer mode
    - click "Load unpacked" (or equivalent in Edge etc)
    - navigate into the folder containing the extension files
    - click "Select Folder"
    - it should install and load, there will be an error prompt on the extension card
        - clicking it should show it's because it's Manifest v2, you can dismiss the error if you want

I hope that helps! Let me know if you have questions.

edit: the truly annoying part about the Manifest v3 changes is they were made supposedly for more secure, safer extensions... and there's already been one v3 extension reported that got through all the checks, and was still hijacking information. All this red tape and it still didn't work.

**Comment by MaNaReaver** [comment]
Hey again,

Thank you so much for providing elaborate, clear and detailed instructions to create an extension from the GitHub build. I was successfully able to install the extension and try it out myself, but it appears that the extension is unable to automatically block or mute people as it should. There are no errors aside from the Deprecated Manifest v2 error, and I've added the required blocking and whitelisting keywords that should trigger a block. This has also been an issue with the original extension, which has stopped working for the past three months, and could possibly be due to some recent changes made to the platform. Is the extension working for you on any chromium browsers lately? Appreciate your help and suggestions, and thanks again for your your time and inputs to improving the original extension.

Best regards.

**Comment by blockindouches** [comment]
EDITS: bunch of clarifications

You are correct, I just tested with Chrome, Edge and Opera, and none of them work with the extension now, must be something disabling some Manifest v2 functionality, even though the extension loads.

[Firefox Developer](https://www.mozilla.org/en-US/firefox/developer/) and [Librewolf](https://librewolf.net/) both still work just fine, pops the confirm notifications and adds to the mute/block list without issue. Librewolf didn't even require me to put it into developer mode (not sure there is a developer mode.) **(EDIT: Librewolf has no developer mode, but you still have to override the requirement for extension signing in "about:config" as described in the previous reply for Firefox browsers.)**

So at least we know there were no changes to the Twitter website that disabled it, only chromium changes. So at this time it is definitely a Firefox derivative-only extension. Which may be better anyway since Google keeps doing things to Chrome and apparently those changes have propagated through all chromium browsers, and Firefox is generally considered more secure and customizable. Firefox used to be significantly slower than Chrome, but recent changes have them at pretty even speeds now.

If you're not against it for some reason, I would recommend installing [Librewolf](https://librewolf.net/) (a security-hardened fork of Firefox), and just use that as your social media browser. They don't come installed by default on Librewolf, but you can also add the [Facebook Container](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) and [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) extensions to isolate platforms from each other and prevent cross-website tracking. [Librewolf also has a portable version](https://librewolf.net/installation/windows/) that you can run off a USB drive from any computer, and it should preserve all the extension whitelist data so you don't keep getting prompts to block/mute the same accounts.

Also, if you're not aware of it, this version of [Blue Blocker](https://addons.mozilla.org/en-US/firefox/addon/blue-blocker/) is really good for autoblock or muting of ad promoting accounts. You have to be careful with it if you don't want to block all blue checks, I generally set it to a really low threshhold so it mainly targets ad accounts and low follower accounts, and then let my keywords in DoucheBlock handle the rest.

Doing that should also isolate you from any future changes to Firefox Developer that may break the extension, you just update or download a new portable for Librewolf if you need to for some reason, and if any version breaks the extension you just revert to the old browser. The nice thing about portable versions is several versions can exist next to each other in different folders, so as long as social media websites don't make any breaking changes (I guess we only care about Twitter here), using an older browser for them/it shouldn't be an issue.

If in the future Elon actually converts the whole website and the API calls to "x.com", I'll have to update the extension. It will currently work now if they only change the regular links to "x.com", but if the API access points change, I'll have to update the extension to the new domain. My main hope there is that he doesn't somehow disable the API access the original dev used in the original extension, because I'm not sure I could fix that problem.

**Comment by blockindouches** [comment]
I've uploaded an unsigned release for Firefox: https://github.com/blockindouches/doucheblockplus/releases

Feel free to still build your own from source. Be aware that I realized I forgot to change the extension name and version number in the build .json files to reflect it's a new extension separate from original DoucheBlock, etc. If you download the new source by any method, it will now show 1.0.0 (I just decided to reset to square one for now) and some other details are corrected. 

The extension id for Firefox in the manifest file is the correct one assigned to this new DoucheBlockPlus by Mozilla's developer portal, even though it hasn't made it through the approval process yet. You get one automatically assigned on the initial submission for approval, and that won't change for this plugin. Either it gets approved and allowed in the store, or it becomes an abandoned id that doesn't get assigned to other plugins.

**Pull request merged**
